### ISSUE TITLE
`notIsEquiv` missing

### ISSUE THREAD

**Issue by fredefox** [Saizan/cubical-demo#11]
Did you forget to commit `notIsEquiv`?

https://github.com/Saizan/cubical-demo/blob/87c2dcad5053459e095c14e91bb2dffa7032f46b/AIM_Demo/DemoUniv.agda#L9

**Comment by Saizan** [comment]
Have you pulled recently?
it's there:
https://github.com/Saizan/cubical-demo/blob/master/NotIsEquiv.agda#L17
