### ISSUE TITLE
Can't build project

### ISSUE THREAD

**Issue by fredefox** [Saizan/cubical-demo#3]
@Saizan, can you give me the version of [`agda-stdlib`](https://github.com/agda/agda-stdlib) and [`agda`](https://github.com/agda/agda) that you've successfully managed to build this project with?

On my system:

```
§ agda --version
Agda version 2.6.0-47bba7d
§ cd ~/.agda/libs/agda-stdlib && git show
commit d3df3e41156ba4981dd1e08784cc5bfd94999184
...
§ cd ~/workspace/cubical-demo && agda --cubical Everything.agda
...
~/workspace/cubical-demo/Id.agda:12,27-32
PathP (λ _ → .A) .x (ouc y) !=< Path' (_x_24 φ w) (_y_25 φ w) of
type Set .a
when checking that the expression ouc w has type
Path' (_x_24 φ w) (_y_25 φ w)
```

**Comment by Saizan** [comment]
Should be fixed by 63976dccd73cb2626aa4478be1c02453b255afa7

Building Everything wasn't part of my tests so something slipped up. Thanks for reporting this
