### ISSUE TITLE
Error in Sigma.agda

### ISSUE THREAD

**Issue by m0davis** [Saizan/cubical-demo#8]
Using the latest (or nearly-so) `master` versions of agda and the standard library, I get an error when trying to load Sigma.agda. The error is:

    ...cubical-demo/Sigma.agda:103,61-63
    (Set ℓ') !=< (PathP (λ _ → Set ℓ') (_a_440 t u p) (_x_441 t u p))
    of type (Set (ℓ-suc ℓ'))
    when checking that the expression T0 has type
    Path (_a_440 t u p) (_x_441 t u p)

**Comment by Saizan** [comment]
Thanks! Fixed with ce599ac67c653c196ef53285218f97f4925224b3 .
